In [ ]:
##Numpy is a python library was created in 2005 by travis olpihant numpy is used
##for working with arrays .Numpy is short for "Numerical Python" 50x faster than python list


In [1]:
#importing numpy library
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)


[1 2 3 4]


different ways to create many arrays

In [2]:
#to create an ndarray we can pass a list tuple or
##other array like object
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [3]:
##to see the dimension of array
print(arr3.ndim)

2


In [8]:
##create a 3d array
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4.ndim)

2


In [11]:
##Numpy Array indexing
array5=np.array([1,2,3,4,5])
print(array5[2])

3


In [16]:
print(array5[0:3])

[1 2 3]


In [17]:
print(array5[0:3])
#using negative index
print(array5[-1])
print(array5[-2:-1])

[1 2 3]
5
[4]


Ques:get third and fourth element in the following way

In [18]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [23]:
import numpy as np
arr=np.array([[1,2,3,4],[4,5,6,9]])
print(arr)
print('2nd element on 1st row',arr[0,1])

[[1 2 3 4]
 [4 5 6 9]]
2nd element on 1st row 2


Access the element on the 2nd row 5th collumn

In [24]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('5th element on the 2nd row',arr[1][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on the 2nd row 10


In [25]:
import numpy as np
arr=np.array([[[1,2,3],[6,7,8]],[[9,10,11],[12,13,14]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]
8


print the last element from 2nd dim

In [26]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('last element from 2nd dim',arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
last element from 2nd dim 10


Slice array of elements from index 1to index 5 from the following

In [27]:
import numpy as np
arr=np.array([10,20,30,40,50,60,75])
print(arr[1:5])

[20 30 40 50]


Slice elements from index 4 to the end of array

In [28]:
import numpy as np
arr=np.array([10,20,30,40,50,60,75])
print(arr[4:])

[50 60 75]


slice index from the beginning to indx 4

In [30]:
import numpy as np
arr=np.array([10,20,30,40,50,60,75])
print(arr[:4])

[10 20 30 40]


In [33]:
##negative slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [35]:
##use the step value to determine the step of slicing
print(arr[1:5:2])
##return every other element from the array
print(arr[::2])

[2 4]
[1 3 5 7]


In [36]:
##slicing 2-D Arrays
## from the second element slice element from index 1 to index 4
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [40]:
##from both element return index 2
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])
print(arr[0:2,1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [41]:
##data types in numpy
##Numpy has some extra data types and refer to data types with one character
##like i for integers,u for unsigned integers etc
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [43]:
##create an array with define data types
import numpy as np
arr=np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [46]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [47]:
import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [48]:
##Change data type from float to integer by using 'i' as parameter value
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [53]:
##Numpy array copyvs view
##the main difference between a copy and a view of an array is that the copy is a new array
##and the view is just a view of the original array
#make a copy,change the original array,and display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
x=arr.copy()
print(x)
arr[0]=42
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]
[42  2  3  4  5]


In [55]:
##make a view,change the original array and display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
print("Original array",arr)
print(arr)
x=arr.view()
print(x)
arr[0]=42
print(arr)

Original array [1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[42  2  3  4  5]


In [56]:
##Numpy array Shape
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [57]:
##Numpy reshaping array re-shape from 1D to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
##we can reshape (-1) to do this
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [59]:
##Numpy Array iterating
##iterating means going through elements one by one
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3
